MCE = {
	"mode": "exact",
	"elements": "id_text",
	"theme": "advanced",
	"language": "ru",
	"plugins": "safari,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,images",
	"theme_advanced_buttons1": "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,formatselect,fontsizeselect,|,cut,copy,paste,pastetext,pasteword,|,bullist,numlist,",
	"theme_advanced_buttons2": ",code,|,undo,redo,|,link,images,|,tablecontrols,|,outdent,indent,|,forecolor,backcolor,removeformat,",
	"theme_advanced_buttons3": "",
	"theme_advanced_toolbar_location": "top",
	"theme_advanced_blockformats": "p,div,address,h2,h3,h4",
	"theme_advanced_toolbar_align": "left",
	"theme_advanced_statusbar_location": "bottom",
	"theme_advanced_resizing": True,
	"relative_urls": False,
	"paste_auto_cleanup_on_paste": True,
	"content_css": "/media/css/",
	"template_external_list_url": "js/template_list.js",
	"external_link_list_url": "js/link_list.js",
	"external_image_list_url": "js/image_list.js",
	"media_external_list_url": "js/media_list.js"
}

new_MCE = {
	"mode": "exact",
	"elements": "id_text",
	"theme": "advanced",
	"language": "ru",
	"plugins": "safari,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,images",
	"theme_advanced_buttons1": "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,formatselect,fontsizeselect,|,cut,copy,paste,pastetext,pasteword,|,bullist,numlist,",
	"theme_advanced_buttons2": ",code,|,undo,redo,|,link,|,tablecontrols,|,outdent,indent,|,forecolor,backcolor,removeformat,",
	"theme_advanced_buttons3": "",
	"theme_advanced_toolbar_location": "top",
	"theme_advanced_blockformats": "p,div,address,h2,h3,h4",
	"theme_advanced_toolbar_align": "left",
	"theme_advanced_statusbar_location": "bottom",
	"theme_advanced_resizing": True,
	"relative_urls": False,
	"paste_auto_cleanup_on_paste": True,
	"content_css": "/media/css/",
	"template_external_list_url": "js/template_list.js",
	"external_link_list_url": "js/link_list.js",
	"external_image_list_url": "js/image_list.js",
	"media_external_list_url": "js/media_list.js"
}
